### ISSUE TITLE
Update relative URLs to point to correct location

### ISSUE THREAD

**Issue by ottok** [fmarcia/UglifyCSS#12] opened 2013-11-26 10:14 UTC
Hello,

If I run something like
```
uglifycss /css/ie.css css/output.css css/styles.css adminbar/css/adminbar.css bootstrap/css/bootstrap.css themes/seravo.css
```

.. but in the resulting CSS many of the images will point to wrong locations, eg. '../img/xyz.png' when it should be 'adminbar/img/xyz.png'. 

Is UglifyCSS supposed to update relative URLs so that the point to the correct location?

**Comment by futureweb** [comment] 2016-09-12 13:22
We would also like to see relative URLs automatically fixed if final CSS is in another Location than the Original CSS Files ...
So we could simply update CSS Files of Libraries we are using - without worrying to forget fixing IMG Pathes within ...

Andreas Schnederle-Wagner

**Comment by futureweb** [comment] 2016-10-14 08:55
@fmarcia - That's good News indead - I will test is as soon as NPM got the new 0.0.22 Package! ;-)

**Comment by fmarcia** [comment] 2016-10-14 18:15
@futureweb I just published changes on npm. Your test report is welcome, especially if you run it on windows

**Comment by futureweb** [comment] 2016-10-18 11:40
@fmarcia - already struggle with first tests :-/
No matter how I call uglifycss with "--convert-urls" Param it always fails with "unable to process "test.css" with TypeError: Object test has no method 'fill'" 

uglifycss --convert-urls '/test/' test.css > test-gen.css 
uglifycss --convert-urls /test/ test.css > test-gen.css 
uglifycss --convert-urls "/test/" test.css > test-gen.css 
uglifycss --convert-urls='/test/' test.css > test-gen.css 
...

?!

**Comment by fmarcia** [comment] 2016-10-18 14:58
The right syntax is `uglifycss --convert-urls /test/ test.css > test-gen.css`.
Could you publish the content of test.css? Thanks.

**Comment by futureweb** [comment] 2016-10-18 15:03
> [root@server tmp]# cat test.css 
>/* Replace PNGs with SVGs for capable browsers (excluding IE<9) */
>body:last-child .blueimp-gallery > .slides > .slide-error {
>  background-image: url("/js/jquery/blueimp_Gallery/img/error.svg");
>}
>/* Replace PNGs with SVGs for capable browsers (excluding IE<9) */
>body:last-child .blueimp-gallery1 > .slides > .slide-error1 {
>  background-image: url("../img/error.svg");
>}
>[root@server tmp]# uglifycss --convert-urls /test/ test.css > test-gen.css
>unable to process "test.css" with TypeError: Object test has no method 'fill'

**Comment by fmarcia** [comment] 2016-10-18 20:56
@futureweb,
Could you provide versions of uglifycss and nodejs you use?
Also note that `--convert-urls` is the path to the target directory of minified css in your file system

**Comment by futureweb** [comment] 2016-10-18 22:24
@fmarcia 

> [root@server tmp]# cat /etc/redhat-release 
> CentOS release 6.8 (Final)
> [root@server tmp]# node -v
> v0.10.46
> [root@server tmp]# npm -g list uglifycss
> /usr/lib
> `-- uglifycss@0.0.24

**Comment by fmarcia** [comment] 2016-10-19 07:04
@futureweb, I made some tests with your css and couldn't reproduce the error you specified. I guess it may be because of the nodejs version but I'm not that sure. I committed last night a version which displays the full error stack when an error occurs. Could you `git clone` this new version from github and post the error again? Thanks.

**Comment by futureweb** [comment] 2016-10-19 07:39
There you go:

> [root@server tmp]# uglifycss/UglifyCSS/uglifycss --convert-urls /test/ test.css > test-gen.css                      
> uglifycss: unable to process "test.css"
> TypeError: Object test has no method 'fill'
>     at convertRelativeUrls (/tmp/uglifycss/UglifyCSS/uglifycss-lib.js:131:28)
>     at processString (/tmp/uglifycss/UglifyCSS/uglifycss-lib.js:444:15)
>     at Object.processFiles (/tmp/uglifycss/UglifyCSS/uglifycss-lib.js:809:29)
>     at main (/tmp/uglifycss/UglifyCSS/uglifycss:98:31)
>     at Object.<anonymous> (/tmp/uglifycss/UglifyCSS/uglifycss:116:2)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)

maybe it would be beneficial if official Version also got Option to Output Full Error Stack? (maybe with --verbose Parameter or something like that?)

**Comment by fmarcia** [comment] 2016-10-19 08:21
Thank for your help, @futureweb.
It looks like `fill` is not available in node v0.10.46. You can check it by typing, for example, `[1,2].fill("x")` at node prompt. It should raise an error as well. I'm going to use an alternate way to fill the array...
And yes, I will add an option to print the full error stack.

**Comment by futureweb** [comment] 2016-10-19 08:25
@fmarcia - you are right - that's the cause of the Problem. Also getting Error when executing fill on node promt.
Looking forward testing next version without fill ;-)

**Comment by fmarcia** [comment] 2016-10-19 09:08
@futureweb, I'll publish a new version on npm tonight.
Thanks again for your help.

**Comment by futureweb** [comment] 2016-10-19 09:11
@fmarcia - you are welcome - thx for this quick fix! ;-)
Already did some tests - and it's looking good now!

**Comment by futureweb** [comment] 2016-10-19 10:05
@fmarcia - found another little Bug ;-)
When there are Images containing whole Domain - they will break:

> uglifycss/UglifyCSS/uglifycss --convert-urls /tmp/2/3/4/ 1/2/test.css 3/4/5/6/7/1.css > 2/3/4/test-gen.css
-
> background-image:url("http://static.fweb.at/js/jquery/blueimp_Gallery/img/error.svg")
becomes:
> background-image:url("../../../3/4/5/6/7/http:/static.fweb.at/js/jquery/blueimp_Gallery/img/error.svg")

--> uglifycss-lib.js --> Line: 116 - check for "/" is the Problem - guess it would be better to check for starting with ".." ?

**Comment by fmarcia** [comment] 2016-10-19 12:48
I hope so!
Thanks for the catch

**Closed** 2016-10-19 12:57 UTC
Labels: feature request

**Comment by futureweb** [comment] 2016-10-19 13:14
@fmarcia - alright - just did some tests - and it's looking pretty good now! ;-)
thx for superfast bugfixes!

Will deploy on live server when NPM is updated
